Create command/server information
sflynlang/sflynlang-bot pull request #7
Opened 2020-10-01 17:03 UTC by Mikael-R

# Create New Command

Create server-information command to show information about server!

## Issue Number: #3

2020-10-01 17:59 UTC, danielsolartech requested changes

2020-10-01 17:59 UTC, danielsolartech commented on src/commands/general/ServerInformation.ts
> +export default PingCommand;
Change this to `export default ServerInformationCommand;`

2020-10-01 17:59 UTC, danielsolartech commented on src/commands/general/ServerInformation.ts
> +  name: "server-information",
Maybe can be only `server`

2020-10-02 11:42 UTC, Mikael-R commented on src/commands/general/ServerInformation.ts
> +export default PingCommand;
Fixed

2020-10-02 11:42 UTC, Mikael-R commented on src/commands/general/ServerInformation.ts
> +class PingCommand extends Command {
Fixed

2020-10-02 13:53 UTC, danielsolartech approved these changes

2020-10-02 14:02 UTC, merged